[package]
name = "image-util"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
image = "0.23.14"
tiny-skia = "0.6.1"
cgmath = "0.18.0"
anyhow = "1.0"
