[package]
name = "apd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
cgmath = "0.18.0"

[dev-dependencies]
approx = "0.5.0"
